### ISSUE TITLE
compilation error : on go 1.8 + linux

### ISSUE THREAD

**Issue by clashion** [ebfe/scard#4]
Environment: go1.8 , linux

Error during compilation. 

Error Message:
cgo-gcc-prolog:198:2: warning: passing argument 3 of ‘SCardGetStatusChange’ from incompatible pointer type [enabled by default]

/usr/include/PCSC/winscard.h:64:16: note: expected ‘LPSCARD_READERSTATE’ but argument is of type ‘struct <anonymous> *’
  PCSC_API LONG SCardGetStatusChange(SCARDCONTEXT hContext,

**Comment by ebfe** [comment]
Unable to reproduce this. Can you provide more information on what you are trying to compile and what version of pcsclite you have installed?

**Comment by clashion** [comment]
I installed the pcsc-lite via "yum install" , for Centos 7. 
I think it is the version 1.8.20

(https://rpmfind.net/linux/rpm2html/search.php?query=pcsc-lite-devel)
(https://rpmfind.net/linux/rpm2html/search.php?query=pcsc-lite-libs)

I reported separately on golang-nuts forum.
(https://groups.google.com/forum/#!topic/golang-nuts/RuRlP1LQ_M4)

Seems like the issue is related to go1.8 cgo on linux.

**Comment by clashion** [comment]
Although there is warning message during compilation (issue which will be fixed in go1.9), the compilation could complete and the code generated can interface with pc/sc. 
Hence, I can close this issue.
